services:
  - type: web
    name: benu-startup-bot
    env: python
    plan: free
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GOOGLE_CREDENTIALS
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: PORT
        value: 8080
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          type: web
          property: hostname
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /health